package parser

import (
	"fmt"
	"strings"
)

// converts .spidey into .go
func TranspileToGo(componentName string, rawContent string) (string, error) {
	parsed, err := Parse(rawContent)
	if err != nil {
		return "", err
	}

	exportedName := strings.Title(componentName)

	// remove HTML backticks to avoid breaking Go raw string literals
	safeHTML := strings.ReplaceAll(parsed.HTML, "`", "` + \"`\" + `")

	var builder strings.Builder
	builder.WriteString("// Code generated by Spidey. DO NOT EDIT.\n")
	builder.WriteString("package pages\n\n")
	builder.WriteString("import (\n\t\"bytes\"\n\t\"html/template\"\n)\n\n")

	// Inject server-side logic and structs directly
	if parsed.GoLogic != "" {
		builder.WriteString("// --- User Backend Frontmatter ---\n")
		builder.WriteString(parsed.GoLogic)
		builder.WriteString("\n// --------------------------------\n\n")
	}

	// Generate a type-safe Render function
	builder.WriteString(fmt.Sprintf("func Render%s(data interface{}) (string, error) {\n", exportedName))
	builder.WriteString(fmt.Sprintf("\ttmpl, err := template.New(\"%s\").Parse(`%s`)\n", componentName, safeHTML))
	builder.WriteString("\tif err != nil {\n\t\treturn \"\", err\n\t}\n")
	builder.WriteString("\tvar buf bytes.Buffer\n")
	builder.WriteString("\terr = tmpl.Execute(&buf, data)\n")
	builder.WriteString("\treturn buf.String(), err\n")
	builder.WriteString("}\n")

	return builder.String(), nil
}
