package parser

import (
	"fmt"
	"regexp"
	"strings"
)

// TranspileToGo converts .spidey into .go
func TranspileToGo(componentName string, rawContent string, appLayout string, components string) (string, error) {
	parsed, err := Parse(rawContent)
	if err != nil {
		return "", err
	}

	re := regexp.MustCompile(`<([A-Z][a-zA-Z0-9]*)\s*/>`)

	parsedComponents := re.ReplaceAllString(components, `{{template "$1" .}}`)
	parsedHTML := re.ReplaceAllString(parsed.HTML, `{{template "$1" .}}`)

	// Wrap the page content inside the appLayout if it exists
	var finalHTML string
	if appLayout != "" {
		// Convert components inside the layout file
		parsedLayout := re.ReplaceAllString(appLayout, `{{template "$1" .}}`)

		// Put component definitions outside content block
		finalHTML = parsedLayout + "\n" + parsedComponents + "\n{{define \"content\"}}\n" + parsedHTML + "\n{{end}}"
	} else {
		finalHTML = parsedComponents + "\n" + parsedHTML
	}

	// remove HTML backticks to avoid breaking Go raw string literals
	safeHTML := strings.ReplaceAll(finalHTML, "`", "` + \"`\" + `")

	var builder strings.Builder
	builder.WriteString("// Code generated by Spidey. DO NOT EDIT.\n")
	builder.WriteString("package pages\n\n")
	builder.WriteString("import (\n\t\"bytes\"\n\t\"html/template\"\n)\n\n")

	// Inject server-side logic and structs directly
	if parsed.GoLogic != "" {
		builder.WriteString("// --- User Backend Frontmatter ---\n")
		builder.WriteString(parsed.GoLogic)
		builder.WriteString("\n// --------------------------------\n\n")
	}

	// Generate the auto-registering init block
	builder.WriteString("func init() {\n")
	builder.WriteString(fmt.Sprintf("\tRegister(\"%s\", func(data interface{}) (string, error) {\n", componentName))
	builder.WriteString(fmt.Sprintf("\t\ttmpl, err := template.New(\"%s\").Parse(`%s`)\n", componentName, safeHTML))
	builder.WriteString("\t\tif err != nil {\n\t\t\treturn \"\", err\n\t\t}\n")
	builder.WriteString("\t\tvar buf bytes.Buffer\n")
	builder.WriteString("\t\terr = tmpl.Execute(&buf, data)\n")
	builder.WriteString("\t\treturn buf.String(), err\n")
	builder.WriteString("\t})\n")
	builder.WriteString("}\n")

	return builder.String(), nil
}
