package main

import (
	"embed"
	"fmt"
	"os"
	"os/exec"
	"strings"

	"spidey/internal/bundler"
	"spidey/internal/config"
	"spidey/internal/dev"
)

//go:embed templates/*
var starterTemplates embed.FS

func main() {
	if len(os.Args) < 2 {
		fmt.Println("Usage: spidey [init|dev|build]")
		os.Exit(1)
	}

	command := os.Args[1]
	currentDir, _ := os.Getwd()

	switch command {
	case "init":
		var projectName string
		if len(os.Args) > 2 {
			projectName = os.Args[2]
		}
		initProject(projectName)
	case "dev":
		fmt.Println("Starting Spidey development environment...")
		cfg := config.LoadConfig(currentDir)
		// Pass starterTemplates to the watcher
		dev.StartWatcher(currentDir, starterTemplates, cfg)
	case "build":
		fmt.Println("Spidey: Transpiling pages...")
		cfg := config.LoadConfig(currentDir)
		// Pass starterTemplates to the build engine
		if err := bundler.ProcessPages(currentDir, starterTemplates, "", cfg); err != nil {
			fmt.Printf("Engine Error: %v\n", err)
			os.Exit(1)
		}

		fmt.Println("Spidey: Compiling final binary...")
		if err := bundler.CompileBinary(currentDir, cfg); err != nil {
			fmt.Printf("Compilation Error: %v\n", err)
			os.Exit(1)
		}

		fmt.Printf("Build successful! Executable is in ./%s\n", cfg.Directories.OutputDir)
	case "export":
		fmt.Println("Spidey: Transpiling pages for static export...")
		cfg := config.LoadConfig(currentDir)
		if err := bundler.ProcessPages(currentDir, starterTemplates, "", cfg); err != nil {
			fmt.Printf("Engine Error: %v\n", err)
			os.Exit(1)
		}

		fmt.Println("Spidey: Compiling temporary SSG binary...")
		if err := bundler.CompileBinary(currentDir, cfg); err != nil {
			fmt.Printf("Compilation Error: %v\n", err)
			os.Exit(1)
		}

		// Run the generated binary with --export
		exportCmd := exec.Command(fmt.Sprintf("./%s", cfg.Directories.OutputDir), "--export")
		exportCmd.Dir = currentDir
		exportCmd.Stdout = os.Stdout
		exportCmd.Stderr = os.Stderr
		if err := exportCmd.Run(); err != nil {
			fmt.Printf("Export Error: %v\n", err)
			os.Exit(1)
		}
	default:
		fmt.Printf("Unknown command: %s\n", command)
	}
}

func initProject(projectName string) {
	if projectName != "" {
		fmt.Printf("Initializing Go module: %s\n", projectName)
		cmd := exec.Command("go", "mod", "init", projectName)
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		if err := cmd.Run(); err != nil {
			fmt.Printf("Warning: Failed to initialize Go module: %v\n", err)
		}
	}

	// Create workspace folders
	dirs := []string{"api", "pages", "components", "public"}
	for _, dir := range dirs {
		os.MkdirAll(dir, 0755)
	}

	os.MkdirAll("lib/pages", 0755)
	os.MkdirAll("lib/router", 0755)

	// Inject  Router Code
	routerCodeBytes, err := starterTemplates.ReadFile("templates/router.go")
	if err == nil {
		routerCode := string(routerCodeBytes)
		routerCode = strings.Replace(routerCode, "//go:build ignore", "", 1)

		routerCode = strings.TrimSpace(routerCode) + "\n"

		os.WriteFile("lib/router/router.go", []byte(routerCode), 0644)
	} else {
		fmt.Println("Warning: Failed to inject router code.")
	}

	// Inject Dynamic Registry (Base File)
	baseCodeBytes, err := starterTemplates.ReadFile("templates/base.go")
	if err == nil {
		baseCode := string(baseCodeBytes)
		baseCode = strings.Replace(baseCode, "//go:build ignore", "", 1)
		baseCode = strings.TrimSpace(baseCode) + "\n"

		os.WriteFile("lib/pages/base.go", []byte(baseCode), 0644)
	} else {
		fmt.Println("Warning: Failed to inject base code.")
	}

	// Setup configs
	gitignore := "lib/\nbin/\n.env\n"
	os.WriteFile(".gitignore", []byte(gitignore), 0644)

	// Create a placeholder routes file to prevent "undefined: pages.RegisterRoutes" errors
	importPath := "testapp"
	if projectName != "" {
		importPath = projectName
	}
	placeholderRoutes := fmt.Sprintf(`// Code generated by Spidey. DO NOT EDIT.
package pages

import (
	"%s/lib/router"
)

func RegisterRoutes(app *router.App) {
	// Auto-generated routes will be injected here during build/dev
}
`, importPath)
	os.WriteFile("lib/pages/routes.go", []byte(placeholderRoutes), 0644)

	fmt.Println("Spidey workspace created successfully")
}
