package main

import (
	"embed"
	"fmt"
	"os"
	"strings"

	"spidey/pkg/bundler"
	"spidey/pkg/dev"
)

//go:embed templates/*
var starterTemplates embed.FS

func main() {
	if len(os.Args) < 2 {
		fmt.Println("Usage: spidey [init|dev|build]")
		os.Exit(1)
	}

	command := os.Args[1]
	currentDir, _ := os.Getwd()

	switch command {
	case "init":
		initProject()
	case "dev":
		fmt.Println("Starting Spidey development environment...")
		// Pass starterTemplates to the watcher
		dev.StartWatcher(currentDir, starterTemplates)
	case "build":
		fmt.Println("Spidey: Transpiling pages...")
		// Pass starterTemplates to the build engine
		if err := bundler.ProcessPages(currentDir, starterTemplates, false); err != nil {
			fmt.Printf("Engine Error: %v\n", err)
			os.Exit(1)
		}

		fmt.Println("Spidey: Compiling final binary...")
		if err := bundler.CompileBinary(currentDir); err != nil {
			fmt.Printf("Compilation Error: %v\n", err)
			os.Exit(1)
		}

		fmt.Println("Build successful! Executable is in ./bin/server")
	default:
		fmt.Printf("Unknown command: %s\n", command)
	}
}

func initProject() {
	// Create standard workspace folders
	dirs := []string{"api", "pages", "components", "public"}
	for _, dir := range dirs {
		os.MkdirAll(dir, 0755)
	}

	// Create lib file to store generated code
	os.MkdirAll("lib/pages", 0755)
	os.MkdirAll("lib/router", 0755)

	// Inject the Router Code
	routerCodeBytes, err := starterTemplates.ReadFile("templates/router.go")
	if err == nil {
		routerCode := string(routerCodeBytes)
		routerCode = strings.Replace(routerCode, "//go:build ignore", "", 1)

		routerCode = strings.TrimSpace(routerCode) + "\n"

		os.WriteFile("lib/router/router.go", []byte(routerCode), 0644)
	} else {
		fmt.Println("Warning: Failed to inject router code.")
	}

	// Inject the Dynamic Registry (Base File)
	baseCodeBytes, err := starterTemplates.ReadFile("templates/base.go")
	if err == nil {
		// Convert to string and strip out the ignore tag
		baseCode := string(baseCodeBytes)
		baseCode = strings.Replace(baseCode, "//go:build ignore", "", 1)
		baseCode = strings.TrimSpace(baseCode) + "\n"

		os.WriteFile("lib/pages/base.go", []byte(baseCode), 0644)
	} else {
		fmt.Println("Warning: Failed to inject base code.")
	}

	// Setup configs
	gitignore := "lib/\nbin/\n.env\n"
	os.WriteFile(".gitignore", []byte(gitignore), 0644)

	// Create a placeholder routes file to prevent "undefined: pages.RegisterRoutes" errors in IDEs before the first build
	placeholderRoutes := `// Code generated by Spidey. DO NOT EDIT.
package pages

import (
	"testapp/lib/router"
)

func RegisterRoutes(app *router.App) {
	// Auto-generated routes will be injected here during build/dev
}
`
	os.WriteFile("lib/pages/routes.go", []byte(placeholderRoutes), 0644)

	fmt.Println("Spidey workspace created successfully")
}
