package parser

import (
	"fmt"
	"regexp"
	"strings"
)

// converts .spidey into .go
func TranspileToGo(modName string, componentName string, rawContent string, appLayout string, components string, globalStyles *strings.Builder) (string, error) {
	parsed, err := Parse(componentName, rawContent)
	if err != nil {
		return "", err
	}

	if parsed.Styles != "" && globalStyles != nil {
		globalStyles.WriteString(parsed.Styles + "\n")
	}

	re := regexp.MustCompile(`(?s)<([A-Z][a-zA-Z0-9]*)([^>]*)/>`)

	replaceFunc := func(match string) string {
		submatch := re.FindStringSubmatch(match)
		if len(submatch) == 3 {
			compName := submatch[1]
			attrs := submatch[2]
			if strings.Contains(attrs, "client:load") {
				return fmt.Sprintf(`<spidey-island data-component="%s">{{template "%s" .}}</spidey-island>`, compName, compName)
			}
			return fmt.Sprintf(`{{template "%s" .}}`, compName)
		}
		return match
	}

	parsedComponents := re.ReplaceAllStringFunc(components, replaceFunc)
	parsedHTML := re.ReplaceAllStringFunc(parsed.HTML, replaceFunc)

	// Wrap the page content inside the appLayout if it exists
	var finalHTML string
	if appLayout != "" {
		// Convert components inside the layout file
		parsedLayout := re.ReplaceAllStringFunc(appLayout, replaceFunc)

		// Put component definitions outside content block
		finalHTML = parsedLayout + "\n" + parsedComponents + "\n{{define \"content\"}}\n" + parsedHTML + "\n{{end}}"
	} else {
		finalHTML = parsedComponents + "\n" + parsedHTML
	}

	// remove HTML backticks
	safeHTML := strings.ReplaceAll(finalHTML, "`", "` + \"`\" + `")

	var builder strings.Builder
	builder.WriteString("// Code generated by Spidey. DO NOT EDIT.\n")
	builder.WriteString("package pages\n\n")
	builder.WriteString("import (\n\t\"bytes\"\n\t\"html/template\"\n")
	builder.WriteString(fmt.Sprintf("\t\"%s/api/spidey\"\n", modName))
	builder.WriteString(")\n\n")

	// Inject server-side logic and structs directly
	if parsed.GoLogic != "" {
		builder.WriteString("// --- User Backend Frontmatter ---\n")
		builder.WriteString(parsed.GoLogic)
		builder.WriteString("\n// --------------------------------\n\n")
	}

	// Generate the auto-registering init block
	builder.WriteString("func init() {\n")
	builder.WriteString(fmt.Sprintf("\tspidey.Register(\"%s\", func(data interface{}) (string, error) {\n", componentName))
	builder.WriteString(fmt.Sprintf("\t\ttmpl, err := template.New(\"%s\").Parse(`%s`)\n", componentName, safeHTML))
	builder.WriteString("\t\tif err != nil {\n\t\t\treturn \"\", err\n\t\t}\n")
	builder.WriteString("\t\tvar buf bytes.Buffer\n")
	builder.WriteString("\t\terr = tmpl.Execute(&buf, data)\n")
	builder.WriteString("\t\treturn buf.String(), err\n")
	builder.WriteString("\t})\n")
	builder.WriteString("}\n")

	return builder.String(), nil
}
