package parser

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"

	"github.com/saviru/spidey/pkg/sandbox"
)

var attrRe = regexp.MustCompile(`([a-zA-Z_:][a-zA-Z0-9_:-]*)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'=<>` + "`" + `]+)))?`)

func parseComponentAttrs(attrs string) (bool, string) {
	isIsland := false
	matches := attrRe.FindAllStringSubmatch(attrs, -1)

	var dictArgs []string
	for _, m := range matches {
		name := m[1]
		if name == "client:load" {
			isIsland = true
			continue
		}

		var val string
		hasValue := false
		if m[2] != "" || strings.Contains(m[0], `="`) {
			val = m[2]
			hasValue = true
		} else if m[3] != "" || strings.Contains(m[0], `='`) {
			val = m[3]
			hasValue = true
		} else if m[4] != "" {
			val = m[4]
			hasValue = true
		}

		if !hasValue {
			// Boolean attribute without explicit value (e.g. <Button disabled />)
			dictArgs = append(dictArgs, strconv.Quote(name), "true")
			continue
		}
		trimmed := strings.TrimSpace(val)
		if strings.HasPrefix(trimmed, "{{") && strings.HasSuffix(trimmed, "}}") {
			// Dynamic expression: title="{{ .title }}" -> "title" .title
			expr := strings.TrimSpace(trimmed[2 : len(trimmed)-2])
			dictArgs = append(dictArgs, strconv.Quote(name), expr)
		} else if strings.HasPrefix(trimmed, ".") || strings.HasPrefix(trimmed, "$") {
			// Pipeline reference: title=.title -> "title" .title
			dictArgs = append(dictArgs, strconv.Quote(name), trimmed)
		} else if trimmed == "true" || trimmed == "false" {
			dictArgs = append(dictArgs, strconv.Quote(name), trimmed)
		} else if m[4] != "" {
			// Unquoted numeric value: count=5 -> "count" 5
			if _, err := strconv.ParseFloat(trimmed, 64); err == nil {
				dictArgs = append(dictArgs, strconv.Quote(name), trimmed)
			} else {
				dictArgs = append(dictArgs, strconv.Quote(name), strconv.Quote(trimmed))
			}
		} else {
			// Quoted string literal: title="Click Me" -> "title" "Click Me"
			dictArgs = append(dictArgs, strconv.Quote(name), strconv.Quote(val))
		}
	}

	if len(dictArgs) == 0 {
		return isIsland, "."
	}

	return isIsland, fmt.Sprintf("(dict %s)", strings.Join(dictArgs, " "))
}

// converts .spidey into .go
func TranspileToGo(modName string, componentName string, rawContent string, appLayout string, components string, globalStyles *strings.Builder) (string, error) {
	parsed, err := Parse(componentName, rawContent)
	if err != nil {
		return "", err
	}

	if parsed.Styles != "" && globalStyles != nil {
		globalStyles.WriteString(parsed.Styles + "\n")
	}

	if parsed.GoLogic != "" {
		if err := sandbox.ValidateFrontmatter(parsed.GoLogic); err != nil {
			return "", fmt.Errorf("[%s] %w", componentName, err)
		}
	}

	re := regexp.MustCompile(`(?s)<([A-Za-z_][a-zA-Z0-9_/-]*)([^>]*)/>`)

	replaceFunc := func(match string) string {
		submatch := re.FindStringSubmatch(match)
		if len(submatch) == 3 {
			compName := submatch[1]
			attrs := submatch[2]
			isIsland, pipeline := parseComponentAttrs(attrs)
			if isIsland {
				return fmt.Sprintf(`<spidey-island data-component="%s">{{template "%s" %s}}</spidey-island>`, compName, compName, pipeline)
			}
			return fmt.Sprintf(`{{template "%s" %s}}`, compName, pipeline)
		}
		return match
	}

	parsedComponents := re.ReplaceAllStringFunc(components, replaceFunc)
	parsedHTML := re.ReplaceAllStringFunc(parsed.HTML, replaceFunc)

	// Wrap the page content inside the appLayout if it exists
	var finalHTML string
	if appLayout != "" {
		// Convert components inside the layout file
		parsedLayout := re.ReplaceAllStringFunc(appLayout, replaceFunc)

		// Put component definitions outside content block
		finalHTML = parsedLayout + "\n" + parsedComponents + "\n{{define \"content\"}}\n" + parsedHTML + "\n{{end}}"
	} else {
		finalHTML = parsedComponents + "\n" + parsedHTML
	}

	// remove HTML backticks
	safeHTML := strings.ReplaceAll(finalHTML, "`", "` + \"`\" + `")

	var builder strings.Builder
	builder.WriteString("// Code generated by Spidey. DO NOT EDIT.\n")
	builder.WriteString("package pages\n\n")
	builder.WriteString("import (\n\t\"bytes\"\n\t\"html/template\"\n")
	builder.WriteString(fmt.Sprintf("\t\"%s/internal/spidey\"\n", modName))
	if parsed.GoLogic != "" {
		builder.WriteString("\t\"github.com/saviru/spidey/pkg/sandbox\"\n")
	}
	builder.WriteString(")\n\n")

	funcName := "render_" + strings.ReplaceAll(strings.ReplaceAll(strings.ReplaceAll(componentName, "/", "_"), "-", "_"), "[", "_")
	funcName = strings.ReplaceAll(funcName, "]", "_")

	hasRenderFunc := regexp.MustCompile(`\bfunc\s+Render\s*\(`).MatchString(parsed.GoLogic)

	if parsed.GoLogic != "" {
		// Rename func Render(...) to func render_pageName(...)
		renamedLogic := regexp.MustCompile(`\bfunc\s+Render\s*\(`).ReplaceAllString(parsed.GoLogic, "func "+funcName+"(")
		builder.WriteString(renamedLogic + "\n")
	}

	builder.WriteString("func init() {\n")
	builder.WriteString(fmt.Sprintf("\tspidey.Register(\"%s\", func(data interface{}) (string, error) {\n", componentName))

	if hasRenderFunc {
		builder.WriteString(fmt.Sprintf("\t\trenderResult := %s()\n", funcName))
		builder.WriteString("\t\tdata = sandbox.MergeParams(renderResult, data)\n\n")
	}

	builder.WriteString(fmt.Sprintf("\t\ttmpl, err := template.New(\"%s\").Funcs(spidey.FuncMap).Parse(`%s`)\n", componentName, safeHTML))

	builder.WriteString("\t\tif err != nil {\n\t\t\treturn \"\", err\n\t\t}\n")
	builder.WriteString("\t\tvar buf bytes.Buffer\n")
	builder.WriteString("\t\terr = tmpl.Execute(&buf, data)\n")
	builder.WriteString("\t\treturn buf.String(), err\n")
	builder.WriteString("\t})\n")
	builder.WriteString("}\n")

	return builder.String(), nil
}
