// Code generated by Spidey. Be cautious when editing this file.

package core

import (
	json "github.com/goccy/go-json"
	"net/http"
	"net/url"
	"strconv" 

	"github.com/go-playground/validator/v10"
)

var validate = validator.New()

type Context struct {
	Writer  http.ResponseWriter
	Request *http.Request
	queryCache url.Values
}

// JSON
// JSON sends a standard JSON response
func (c *Context) JSON(status int, data interface{}) {
	c.Writer.Header().Set("Content-Type", "application/json")
	c.Writer.WriteHeader(status)
	json.NewEncoder(c.Writer).Encode(data)
}

// BindJSON automatically parses the incoming JSON request body into a struct
func (c *Context) BindJSON(obj interface{}) error {
	defer c.Request.Body.Close()
	if err := json.NewDecoder(c.Request.Body).Decode(obj); err != nil {
		return err
	}
	return validate.Struct(obj)
}

// Param retrieves a path parameter (e.g. /users/{id})
func (c *Context) Param(key string) string {
	return c.Request.PathValue(key)
}

// Send returns a raw HTML or text string
func (c *Context) Send(content string) {
	c.Writer.Header().Set("Content-Type", "text/html; charset=utf-8")
	c.Writer.Write([]byte(content))
}

// JSONPretty formats the JSON with tabs and newlines for easier human reading
func (c *Context) JSONPretty(status int, data interface{}) {
	c.Writer.Header().Set("Content-Type", "application/json")
	c.Writer.WriteHeader(status)
	pretty, _ := json.MarshalIndent(data, "", "    ")
	c.Writer.Write(pretty)
}

// SecureJSON prevents JSON Hijacking by prepending "while(1);" if the payload is an array
func (c *Context) SecureJSON(status int, data interface{}) {
	c.Writer.Header().Set("Content-Type", "application/json")
	c.Writer.WriteHeader(status)
	bytes, _ := json.Marshal(data)
	if len(bytes) > 0 && bytes[0] == '[' {
		c.Writer.Write([]byte("while(1);\n"))
	}
	c.Writer.Write(bytes)
}

// PureJSON prevents Go from automatically escaping HTML characters (like < and >) in JSON payloads
func (c *Context) PureJSON(status int, data interface{}) {
	c.Writer.Header().Set("Content-Type", "application/json")
	c.Writer.WriteHeader(status)
	encoder := json.NewEncoder(c.Writer)
	encoder.SetEscapeHTML(false)
	encoder.Encode(data)
}

// JSONP wraps the JSON response inside a Javascript callback function
func (c *Context) JSONP(status int, data interface{}, callback string) {
	c.Writer.Header().Set("Content-Type", "application/javascript")
	c.Writer.WriteHeader(status)
	c.Writer.Write([]byte(callback + "("))
	json.NewEncoder(c.Writer).Encode(data)
	c.Writer.Write([]byte(");"))
}

//Query
// Parses the URL once and caches it for all future calls
func (c *Context) getQueryCache() url.Values {
	if c.queryCache == nil {
		c.queryCache = c.Request.URL.Query()
	}
	return c.queryCache
}

// Returns the string value for a URL query parameter
func (c *Context) Query(key string) string {
	return c.getQueryCache().Get(key)
}

// Returns the query value or a fallback default
func (c *Context) DefaultQuery(key, defaultValue string) string {
	value := c.Query(key)
	if value == "" {
		return defaultValue
	}
	return value
}

// Safely auto-converts a query parameter into an integer
func (c *Context) QueryInt(key string, defaultValue int) int {
	val := c.Query(key)
	if val == "" {
		return defaultValue
	}
	parsed, err := strconv.Atoi(val)
	if err != nil {
		return defaultValue 
	}
	return parsed
}

// safely evaluates boolean query parameters ("true", "1", "yes")
func (c *Context) QueryBool(key string) bool {
	val := c.Query(key)
	return val == "true" || val == "1" || val == "yes"
}

// S-Tags
// Sends a raw HTML fragment back to the Spidey Client Engine
func (c *Context) HTML(status int, htmlFragment string) {
	c.Writer.Header().Set("Content-Type", "text/html; charset=utf-8")
	c.Writer.WriteHeader(status)
	c.Writer.Write([]byte(htmlFragment))
}
