// Code generated by Spidey. Be cautious when editing this file.

package core

import (
	"fmt"
	"io"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"strings"
)

func copyDir(src, dst string) error {
	return filepath.Walk(src, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		relPath, _ := filepath.Rel(src, path)
		dstPath := filepath.Join(dst, relPath)
		if info.IsDir() {
			return os.MkdirAll(dstPath, 0755)
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		return os.WriteFile(dstPath, data, 0644)
	})
}

func (a *App) exportStatic(outDir string) error {
	fmt.Println("Spidey: Exporting static site to ./" + outDir)
	os.MkdirAll(outDir, 0755)

	if _, err := os.Stat("public"); err == nil {
		copyDir("public", outDir)
	}

	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		return err
	}
	port := listener.Addr().(*net.TCPAddr).Port

	go http.Serve(listener, a.mux)

	for route := range a.registered {
		isDynamic := strings.Contains(route, "{") && !strings.Contains(route, "{$}")
		if isDynamic || strings.Contains(route, "/api/") || strings.Contains(route, "/livereload") {
			continue
		}

		parts := strings.Split(route, " ")
		originalPath := parts[len(parts)-1]

		requestPath := originalPath
		if strings.HasSuffix(requestPath, "{$}") {
			requestPath = strings.TrimSuffix(requestPath, "{$}")
		}

		filePath := requestPath
		if filePath == "/" || filePath == "" {
			filePath = "/index"
		}

		resp, err := http.Get(fmt.Sprintf("http://127.0.0.1:%d%s", port, requestPath))
		if err != nil {
			continue
		}

		body, _ := io.ReadAll(resp.Body)
		resp.Body.Close()

		savePath := filepath.Join(outDir, filePath)
		if savePath == outDir || savePath == filepath.Join(outDir, "index") {
			savePath = filepath.Join(outDir, "index.html")
		} else {
			savePath = savePath + ".html"
		}

		os.MkdirAll(filepath.Dir(savePath), 0755)
		os.WriteFile(savePath, body, 0644)
		fmt.Println(" ✓ " + filePath)
	}

	fmt.Println("Spidey: Export complete!")
	return nil
}
