// Code generated by Spidey. Be cautious when editing this file.

package core

import (
	"fmt"
	"net"
	"net/http"
	"os"
	"strings"
)

func (a *App) Listen(port ...any) error {
	for _, arg := range os.Args {
		if arg == "--export" {
			return a.exportStatic("out")
		}
	}

	var addr string
	if len(port) > 0 {
		switch v := port[0].(type) {
		case int:
			addr = fmt.Sprintf(":%d", v)
		case string:
			addr = ":" + strings.TrimPrefix(v, ":")
		default:
			return fmt.Errorf("Error: Invalid port type. Port must be an 'int' or 'string'")
		}
	} else {
		addr = fmt.Sprintf(":%d", a.Config.Port)
	}

	listener, err := net.Listen("tcp", addr)
	if err != nil {
		if strings.Contains(err.Error(), "address already in use") {
			return fmt.Errorf("Spidey Error: Port %s is already in use! Please close the other app or change your port", addr)
		}
		return err
	}

	fmt.Printf("Spidey is running on http://localhost%s\n", addr)

	// Apply global middlewares in reverse order so they execute correctly (first added = outermost wrapper)
	var finalHandler http.Handler = a.mux
	for i := len(a.globalMiddlewares) - 1; i >= 0; i-- {
		finalHandler = a.globalMiddlewares[i](finalHandler)
	}

	return http.Serve(listener, finalHandler)
}
