package bundler

import (
	"embed"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"

	"spidey/pkg/parser"

	"github.com/evanw/esbuild/pkg/api"
)

func getModuleName(projectDir string) string {
	content, err := os.ReadFile(filepath.Join(projectDir, "go.mod"))
	if err == nil {
		for _, line := range strings.Split(string(content), "\n") {
			if strings.HasPrefix(line, "module ") {
				return strings.TrimSpace(strings.TrimPrefix(line, "module "))
			}
		}
	}
	return "spideyapp"
}

func ProcessPages(projectDir string, templates embed.FS, isDev bool) error {
	pagesDir := filepath.Join(projectDir, "pages")
	genDir := filepath.Join(projectDir, "lib", "pages")

	os.RemoveAll(genDir)
	os.MkdirAll(genDir, 0755)

	// Read separate base.go template and inject it safely
	baseCodeBytes, err := templates.ReadFile("templates/base.go")
	if err != nil {
		return fmt.Errorf("could not read base.go template: %v", err)
	}
	baseCode := strings.Replace(string(baseCodeBytes), "//go:build ignore", "", 1)
	baseCode = strings.TrimSpace(baseCode) + "\n"

	os.WriteFile(filepath.Join(genDir, "spidey_base.go"), []byte(baseCode), 0644)

	// User Layout Check
	appLayoutStr := ""
	appLayoutPath := filepath.Join(projectDir, "app.spidey")
	if appLayoutBytes, err := os.ReadFile(appLayoutPath); err == nil {
		appLayoutStr = string(appLayoutBytes)

		// Inject scoped CSS stylesheet
		cssLink := `<link rel="stylesheet" href="/assets/spidey.css">`
		if !strings.Contains(appLayoutStr, cssLink) {
			if strings.Contains(appLayoutStr, "</head>") {
				appLayoutStr = strings.Replace(appLayoutStr, "</head>", cssLink+"\n</head>", 1)
			} else {
				appLayoutStr = cssLink + "\n" + appLayoutStr
			}
		}

		// Inject Client Bootstrapper for Islands
		clientScript := `<script src="/assets/spidey-client.js" type="module"></script>`
		if !strings.Contains(appLayoutStr, clientScript) {
			if strings.Contains(appLayoutStr, "</body>") {
				appLayoutStr = strings.Replace(appLayoutStr, "</body>", clientScript+"\n</body>", 1)
			} else {
				appLayoutStr += "\n" + clientScript
			}
		}

		// Inject Livereload if in dev mode
		if isDev {
			script := `<script>const evtSource = new EventSource("http://localhost:3001/livereload");evtSource.onmessage = function(e) { if(e.data === "reload") { setTimeout(() => window.location.reload(), 100); } };</script>`
			if strings.Contains(appLayoutStr, "</body>") {
				appLayoutStr = strings.Replace(appLayoutStr, "</body>", script+"\n</body>", 1)
			} else {
				appLayoutStr += "\n" + script
			}
		}
	}

	componentsDir := filepath.Join(projectDir, "components")
	var componentsBuilder strings.Builder
	var globalStyles strings.Builder

	filepath.WalkDir(componentsDir, func(path string, d fs.DirEntry, err error) error {
		if err == nil && !d.IsDir() && strings.HasSuffix(path, ".spidey") {
			content, _ := os.ReadFile(path)
			name := strings.TrimSuffix(filepath.Base(path), ".spidey")

			parsed, err := parser.Parse(name, string(content))
			if err == nil {
				if parsed.Styles != "" {
					globalStyles.WriteString(parsed.Styles + "\n")
				}
				// Wrap HTML in a Go template define block
				componentsBuilder.WriteString(fmt.Sprintf("\n{{define \"%s\"}}\n%s\n{{end}}\n", name, parsed.HTML))
			}
		}
		return nil
	})

	componentsStr := componentsBuilder.String()

	var routesBuilder strings.Builder
	routesBuilder.WriteString("// Code generated by Spidey. DO NOT EDIT.\n")
	routesBuilder.WriteString("package pages\n\n")
	routesBuilder.WriteString("import (\n")
	routesBuilder.WriteString(fmt.Sprintf("\t\"%s/lib/router\"\n", getModuleName(projectDir)))
	routesBuilder.WriteString(")\n\n")
	routesBuilder.WriteString("func RegisterRoutes(app *router.App) {\n")

	// Transpile .spidey files
	err = filepath.WalkDir(pagesDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if !d.IsDir() {
			if strings.HasSuffix(path, ".jsx") {
				fmt.Println("Error: JSX is not supported in Spidey pages.")
				return nil
			} else if strings.HasSuffix(path, ".js") {
				fmt.Printf("Warning: Please avoid using .js files directly (%s). Use the native .spidey format in pages.\n", filepath.Base(path))
			}
		}

		if !d.IsDir() && strings.HasSuffix(path, ".spidey") {
			content, err := os.ReadFile(path)
			if err != nil {
				return err
			}

			relPath, _ := filepath.Rel(pagesDir, path)
			relPath = filepath.ToSlash(relPath)
			componentName := strings.TrimSuffix(relPath, ".spidey")

			goCode, err := parser.TranspileToGo(componentName, string(content), appLayoutStr, componentsStr, &globalStyles)
			if err != nil {
				return err
			}

			safeName := strings.ReplaceAll(componentName, "/", "_")
			safeName = strings.ReplaceAll(safeName, "[", "")
			safeName = strings.ReplaceAll(safeName, "]", "")
			genPath := filepath.Join(genDir, safeName+"_spidey.go")
			os.WriteFile(genPath, []byte(goCode), 0644)

			routePath := "/" + componentName
			if strings.HasSuffix(routePath, "/index") {
				routePath = strings.TrimSuffix(routePath, "index")
			}
			if routePath != "/" && strings.HasSuffix(routePath, "/") {
				routePath = strings.TrimSuffix(routePath, "/")
			}

			re := regexp.MustCompile(`\[([^\]]+)\]`)
			routePath = re.ReplaceAllString(routePath, `{$1}`)

			routesBuilder.WriteString(fmt.Sprintf("\tapp.GET(\"%s\", func(c *router.Context) {\n", routePath))

			matches := re.FindAllStringSubmatch(componentName, -1)
			if len(matches) > 0 {
				routesBuilder.WriteString("\t\tdata := map[string]interface{}{\n")
				for _, match := range matches {
					param := match[1]
					exportName := strings.ToUpper(param[0:1]) + param[1:]
					routesBuilder.WriteString(fmt.Sprintf("\t\t\t\"%s\": c.Param(\"%s\"),\n", exportName, param))
				}
				routesBuilder.WriteString("\t\t}\n")
				routesBuilder.WriteString(fmt.Sprintf("\t\thtml, err := Render(\"%s\", data)\n", componentName))
			} else {
				routesBuilder.WriteString(fmt.Sprintf("\t\thtml, err := Render(\"%s\", nil)\n", componentName))
			}

			routesBuilder.WriteString("\t\tif err != nil {\n\t\t\tc.Send(\"<h1 style='color:red;'>Template Error</h1><pre>\" + err.Error() + \"</pre>\")\n\t\t\treturn\n\t\t}\n")
			routesBuilder.WriteString("\t\tc.Send(html)\n")
			routesBuilder.WriteString("\t})\n")
		}
		return nil
	})

	routesBuilder.WriteString("}\n")
	os.WriteFile(filepath.Join(genDir, "routes.go"), []byte(routesBuilder.String()), 0644)

	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("transpilation failed: %v", err)
	}

	// Output global styles
	os.MkdirAll(filepath.Join(projectDir, "public", "assets"), 0755)
	os.WriteFile(filepath.Join(projectDir, "public", "assets", "spidey.css"), []byte(globalStyles.String()), 0644)

	// Write spidey-client.js bootstrapper
	clientCode := `
document.addEventListener("DOMContentLoaded", () => {
	const islands = document.querySelectorAll("spidey-island");
	islands.forEach(async (island) => {
		const compName = island.getAttribute("data-component");
		if (compName) {
			try {
				const module = await import("/assets/components/" + compName + ".js");
				if (module.mount) {
					module.mount(island);
				}
			} catch (e) {
				console.error("Spidey: Failed to load island", compName, e);
			}
		}
	});
});
`
	os.WriteFile(filepath.Join(projectDir, "public", "assets", "spidey-client.js"), []byte(clientCode), 0644)

	// esbuild components for islands
	var jsEntries []string
	filepath.WalkDir(componentsDir, func(path string, d fs.DirEntry, err error) error {
		if err == nil && !d.IsDir() {
			if strings.HasSuffix(path, ".jsx") {
				fmt.Println("Error: JSX is not supported in Spidey.")
			} else if strings.HasSuffix(path, ".js") {
				fmt.Printf("Warning: Please avoid using .js files directly (%s). Use the native .spidey format in components.\n", filepath.Base(path))
				jsEntries = append(jsEntries, path)
			}
		}
		return nil
	})

	if len(jsEntries) > 0 {
		fmt.Println("Spidey: Bundling frontend islands...")
		api.Build(api.BuildOptions{
			EntryPoints:       jsEntries,
			Outdir:            filepath.Join(projectDir, "public", "assets", "components"),
			Bundle:            true,
			MinifyWhitespace:  true,
			MinifyIdentifiers: true,
			MinifySyntax:      true,
			Write:             true,
			Format:            api.FormatESModule,
			Splitting:         true,
		})
	}

	return nil
}

func CompileBinary(projectDir string) error {
	cmd := exec.Command("go", "build", "-o", "bin/server.exe", "./api/main.go")
	cmd.Dir = projectDir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}
