//go:build ignore

// Code generated by Spidey. DO NOT EDIT.

package router

import (
	"encoding/json"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/http/httputil"
	"net/url"
	"os"
	"path/filepath"
	"strings"
)

type Context struct {
	Writer  http.ResponseWriter
	Request *http.Request
}

func (c *Context) JSON(status int, data interface{}) {
	c.Writer.Header().Set("Content-Type", "application/json")
	c.Writer.WriteHeader(status)
	json.NewEncoder(c.Writer).Encode(data)
}

func (c *Context) Param(key string) string {
	return c.Request.PathValue(key)
}

func (c *Context) Send(content string) {
	c.Writer.Header().Set("Content-Type", "text/html; charset=utf-8")
	c.Writer.Write([]byte(content))
}

type Middleware func(*Context, func())

// WrapStd natively adapts standard Go middlewares (func(http.Handler) http.Handler) into Spidey's format
func WrapStd(std func(http.Handler) http.Handler) Middleware {
	return func(c *Context, next func()) {
		nextHandler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			c.Writer = w
			c.Request = r
			next()
		})

		wrappedHandler := std(nextHandler)
		wrappedHandler.ServeHTTP(c.Writer, c.Request)
	}
}

type RouterGroup struct {
	prefix      string
	app         *App
	middlewares []Middleware
}

type App struct {
	RouterGroup
	mux        *http.ServeMux
	registered map[string]bool
}

func New() *App {
	app := &App{
		mux:        http.NewServeMux(),
		registered: make(map[string]bool),
	}
	app.RouterGroup = RouterGroup{
		prefix:      "",
		app:         app,
		middlewares: nil,
	}
	return app
}

func (g *RouterGroup) Group(prefix string, middlewares ...any) *RouterGroup {
	var parsedMiddlewares []Middleware
	for _, m := range middlewares {
		switch v := m.(type) {
		case Middleware:
			parsedMiddlewares = append(parsedMiddlewares, v)
		case func(*Context, func()):
			parsedMiddlewares = append(parsedMiddlewares, v)
		case func(http.Handler) http.Handler:
			parsedMiddlewares = append(parsedMiddlewares, WrapStd(v))
		default:
			panic("Error: Unsupported middleware type. Must be Spidey Middleware or standard func(http.Handler) http.Handler")
		}
	}

	newMiddlewares := append([]Middleware{}, g.middlewares...)
	newMiddlewares = append(newMiddlewares, parsedMiddlewares...)

	return &RouterGroup{
		prefix:      g.prefix + prefix,
		app:         g.app,
		middlewares: newMiddlewares,
	}
}

func (g *RouterGroup) Handle(method, path string, handler func(*Context)) {
	fullPath := g.prefix + path

	if fullPath == "/" {
		fullPath = "/{$}"
	}

	route := fullPath
	if method != "ANY" && method != "" {
		route = method + " " + fullPath
	}

	if g.app.registered[route] {
		return // Skip duplicate route
	}
	g.app.registered[route] = true

	g.app.mux.HandleFunc(route, func(w http.ResponseWriter, r *http.Request) {
		ctx := &Context{Writer: w, Request: r}

		index := 0
		var next func()
		next = func() {
			if index < len(g.middlewares) {
				index++
				g.middlewares[index-1](ctx, next)
			} else {
				handler(ctx)
			}
		}
		next()
	})
}

// Proxy routes everything under a path to a microservice
func (g *RouterGroup) Proxy(path string, targetURL string) {
	target, err := url.Parse(targetURL)
	if err != nil {
		panic("invalid target URL for proxy: " + targetURL)
	}
	proxy := httputil.NewSingleHostReverseProxy(target)

	fullPath := g.prefix + path
	if !strings.HasSuffix(fullPath, "/") {
		fullPath += "/"
	}
	trimPrefix := fullPath[:len(fullPath)-1]

	g.Handle("ANY", fullPath, func(c *Context) {
		c.Request.URL.Path = strings.TrimPrefix(c.Request.URL.Path, trimPrefix)
		proxy.ServeHTTP(c.Writer, c.Request)
	})
}

func (g *RouterGroup) GET(path string, handler func(*Context)) {
	g.Handle(http.MethodGet, path, handler)
}
func (g *RouterGroup) POST(path string, handler func(*Context)) {
	g.Handle(http.MethodPost, path, handler)
}
func (g *RouterGroup) PUT(path string, handler func(*Context)) {
	g.Handle(http.MethodPut, path, handler)
}
func (g *RouterGroup) DELETE(path string, handler func(*Context)) {
	g.Handle(http.MethodDelete, path, handler)
}

func (a *App) Listen(port string) error {
	for _, arg := range os.Args {
		if arg == "--export" {
			return a.exportStatic("out")
		}
	}
	return http.ListenAndServe(":"+port, a.mux)
}

func (a *App) Static(prefix, dir string) {
	a.mux.Handle(prefix, http.StripPrefix(prefix, http.FileServer(http.Dir(dir))))
}

func copyDir(src, dst string) error {
	return filepath.Walk(src, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		relPath, _ := filepath.Rel(src, path)
		dstPath := filepath.Join(dst, relPath)
		if info.IsDir() {
			return os.MkdirAll(dstPath, 0755)
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		return os.WriteFile(dstPath, data, 0644)
	})
}

func (a *App) exportStatic(outDir string) error {
	fmt.Println("Spidey: Exporting static site to ./" + outDir)
	os.MkdirAll(outDir, 0755)

	if _, err := os.Stat("public"); err == nil {
		copyDir("public", outDir)
	}

	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		return err
	}
	port := listener.Addr().(*net.TCPAddr).Port

	go http.Serve(listener, a.mux)

	for route := range a.registered {
		if strings.Contains(route, "{") || strings.Contains(route, "/api/") || strings.Contains(route, "/livereload") {
			continue
		}

		parts := strings.Split(route, " ")
		path := parts[len(parts)-1]
		if path == "/" {
			path = "/index"
		} else if strings.HasSuffix(path, "/{$}") {
			path = strings.TrimSuffix(path, "/{$}")
			if path == "" {
				path = "/index"
			}
		}

		resp, err := http.Get(fmt.Sprintf("http://127.0.0.1:%d%s", port, path))
		if err != nil {
			continue
		}

		body, _ := io.ReadAll(resp.Body)
		resp.Body.Close()

		savePath := filepath.Join(outDir, path)
		if savePath == outDir || savePath == filepath.Join(outDir, "index") {
			savePath = filepath.Join(outDir, "index.html")
		} else {
			savePath = savePath + ".html"
		}

		os.MkdirAll(filepath.Dir(savePath), 0755)
		os.WriteFile(savePath, body, 0644)
		fmt.Println(" ✓ " + path)
	}

	fmt.Println("Spidey: Export complete!")
	return nil
}
